[pigeon]
	#Pigeons can spawn naturally in '#envelope:allows_pigeon_spawns' biomes.
	# Default: true
	spawns_naturally = true
	#Pigeons can spawn in the village (similar to Cats).
	# Default: true
	spawns_in_village = true
	#Minimum time (in ticks) that Pigeon will be sitting in a Pigeonhole after entering.
	# Default: 1200
	# Range: > 1
	min_ticks_inside_pigeonhole = 1200
	#Minimum time (in ticks) that Pigeon will spend outside of a Pigeonhole.
	# Default: 2400
	# Range: > 100
	min_ticks_outside_pigeonhole = 2400
	#Time (in ticks) for which Pigeon will be tired after finishing a delivery.
	# Default: 6000
	# Range: > 0
	ticks_tired_after_delivery = 6000
	#Cat will hunt and kill pigeons.
	#Default: true
	hunted_by_cat = true
	#Ocelot will hunt and kill pigeons.
	#Default: true
	hunted_by_ocelot = true
	#Fox will hunt and kill pigeons.
	#Default: true
	hunted_by_fox = true
	#Chance to evade damage while delivering. `#envelope:bypasses_pigeon_delivery_evasion` tag can be used to control which damage types will not be affected.
	# Default: 0.0
	# Range: 0.0 ~ 1.0
	damage_evasion_chance_while_delivering = 0.0
	#Pigeon searches for nearby dropped seeds (envelope:pigeon_food) and eats them.
	eats_seeds = true
	#Pigeon will convert into a Charred Pigeon when it stays in the ultrawarm dimension for some time.
	#Default: true
	convert_into_charred = true
	#Time (in ticks) Pigeon needs to stay in the ultrawarm dimension to convert into Charred Pigeon.
	# Default: 300
	# Range: > 0
	convert_into_charred_ticks = 300

[charred_pigeon]
	#Charred Pigeons can spawn naturally in '#envelope:allows_charred_pigeon_spawns' biomes.
	# Default: true
	spawns_naturally = true
	#Chance of a Charred Pigeon carrying mail when spawned.
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	mail_chance = 0.2
	#Seconds that the target will be ignited for when Charred Pigeon attacks them.
	# Default: 3.0
	# Range: 0.0 ~ 999.0
	ignite_seconds = 3.0
	#Charred Pigeon will convert into a regular Pigeon when it stays outside of the ultrawarm dimension for some time.
	#Default: true
	convert_into_regular = true
	#Time (in ticks) Charred Pigeon needs to stay outside of the ultrawarm dimension to convert into a regular Pigeon.
	# Default: 300
	# Range: > 0
	convert_into_regular_ticks = 300

[pigeonhole]
	#Chance of waste level increasing when pigeon exits the block.
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	waste_level_increase_chance = 0.2
	#Chance of waste level increasing when pigeon exits the block, if it was tired (finished a delivery before resting in a Pigeonhole).
	# Default: 1.0
	# Range: 0.0 ~ 1.0
	waste_level_increase_chance_after_delivery = 1.0
	#Waste from Pigeonhole can be scooped with dispenser that has a shovel (#envelope:waste_scoopable).
	# Default: true.
	dispenser_waste_scooping = true

[mailbox]
	#Levels of experience needed to set or change the address.
	# Default: 3
	# Range: 0 ~ 128
	address_experience_levels_cost = 3

[letter]
	#Letter screen pauses singleplayer game.
	# Default: false
	pause = false
	#Letter will burn and disappear when used on `envelope:burning` blocks. Doesn't apply to Sealed Letters.
	# Default: true
	burning = true
	#Letter will become tattered if a Fox picks it up.
	fox_tattering = true

[package]
	#Holding Sneak while using the Package will unpack and destroy it immediately, instead of opening the menu.
	#Default: true
	sneak_quick_unpack = true
	#Chance of a Package "recycling" back into Paper Box after opening.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	paper_box_return_chance = 0.5
	#Chance of Payback Package "recycling" back into Payback Box after opening, allowing another try to pack the payment.
	# Default: 0.75
	# Range: 0.0 ~ 1.0
	payback_box_return_chance = 0.75

[delivery]
	#Default distance (in blocks) that will be used if distance between two addresses cannot be determined (recipient does not exist, for example).
	# Default: 1500
	# Range: > 1
	default_distance = 1500
	#Courier speed (in blocks per second) while in traveling (background) phases.
	# Default: 20.0
	# Range: 0.01 ~ 9999.0
	courier_travel_speed = 20.0
	#Distance (in blocks) after which travel duration stops increasing and stays at maximum value.
	# Default: 5000
	# Range: > 1
	travel_duration_distance_cap = 5000
	#Delivering pigeons will not spawn when 'doMobSpawning' rule is set to 'false'.
	#Default: false (spawn anyway)
	spawning_respects_domobspawning_rule = false

[payback]
	#'Short' payback request duration (in minutes).
	# Default: 30
	# Range: > 1
	request_duration_short = 30
	#'Medium' payback request duration (in minutes). Default.
	# Default: 180
	# Range: > 1
	request_duration_medium = 180
	#'Long' payback request duration (in minutes).
	# Default: 4320
	# Range: > 1
	request_duration_long = 4320

	[service_addresses.equine_assurance_bureau]
		#A notice letter will be occasionally sent to the player.
		#Default: true
		notice_sending_enabled = true

[misc]
	#Villagers will feed nearby pigeons by throwing them seeds.
	#Requires 'pigeon.eats_seeds' config option to be enabled.
	#Default: true
	villager_feeding_pigeons = true
	#Only Nitwits can feed pigeons.
	#Default: true
	villager_feeding_pigeons_only_nitwits = true
	#Chance of an Archimedes spawning when 'envelope:spawns_archimedes' mob is killed by 'envelope:spawns_archimedes' damage type (player explosion by default).
	# Default: 0.05
	# Range: 0.0 ~ 1.0
	archimedes_chance = 0.05

[debug]
	#Enable debug features. Will negatively impact performance. Don't enable unless it's needed.
	debug_mode = false
