		[types.stone_type.aether]
			holystone = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true

		[types.stone_type.ars_nouveau]
			sourcestone = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true
			cylindrite = true
			cassiterite = true
			rhyolite = true

		[types.stone_type.chronodawn]
			temporal_stone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.deep_aether]
			clorite = true
			raw_clorite = true
			aseterite = true

		[types.stone_type.deeperdarker]
			sculk_stone = true
			gloomslate = true

		[types.stone_type.dndecor]
			cut_stone = true

		[types.stone_type.eternal_starlight]
			grimstone = true
			voidstone = true
			nebulaite = true
			radianite = true
			stellagmite = true
			abysslate = true
			thermabysslate = true
			cryobysslate = true
			springstone = true
			flowglaze = true
			toxite = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.goety]
			shade_stone = true
			crypt_stone = true
			highrock = true
			siltstone = true
			ominous_stone = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.oreganized]
			glance = true

		[types.stone_type.pastel]
			blackslag = true
			preservation_stone = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.scguns]
			phosphorite = true

		[types.stone_type.supplementaries]
			brittlestone = true

		[types.stone_type.twilightforest]
			deadrock = true
			mazestone = true

		[types.stone_type.undergarden]
			depthrock = true
			shiverstone = true
			dreadrock = true
			tremblecrust = true

		[types.stone_type.windswept]
			shale = true
			arkose = true

		[types.stone_type.spelunkery]
			nephrite = true

		[types.stone_type.occultism]
			otherstone = true
			otherrock = true

		[types.stone_type.forbidden_arcanus]
			darkstone = true

		[types.mud_type.deep_aether]
			aether_mud = true

		[types.mud_type.deeperdarker]
			sculk_grime = true

		[types.mud_type.eternal_starlight]
			nightfall_mud = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.chronodawn]
			time_wood = true
			dark_time_wood = true
			ancient_time_wood = true

		[types.wood_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.deeperdarker]
			bloom = true
			echo = true

		[types.wood_type.dimdoors]
			driftwood = true

		[types.wood_type.dungeonsdelight]
			wormwood = true

		[types.wood_type.eidolon_repraised]
			illwood = true

		[types.wood_type.eternal_starlight]
			lunar = true
			northland = true
			banyin = true
			scarlet = true
			torreya = true
			jinglestem = true
			cradlewood = true

		[types.wood_type.goety]
			haunted = true
			rotten = true
			windswept = true
			pine = true
			chorus = true
			corrupt_chorus = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.pastel]
			black = true
			blue = true
			brown = true
			cyan = true
			gray = true
			green = true
			light_blue = true
			light_gray = true
			lime = true
			magenta = true
			orange = true
			pink = true
			purple = true
			red = true
			white = true
			yellow = true
			weeping_gala = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.voidscape]
			thunder = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true
			pine = true

		[types.wood_type.would]
			willow = true
			baobab = true
			ebony = true
			fir = true
			pine = true
			cedar = true
			mahogany = true
			azalea = true
			palm = true
			maple = true
			aspen = true
			walnut = true
			blue_spruce = true

		[types.wood_type.tropicraft]
			mahogany = true
			palm = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

		[types.wood_type.hexalia]
			cottonwood = true
			willow = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			red_archwood = true
			purple_archwood = true
			green_archwood = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_apple_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_apple_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_apple_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_apple_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_apple_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_apple_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true

		[types.leaves_type.chronodawn]
			time_wood = true
			dark_time_wood = true
			ancient_time_wood = true

		[types.leaves_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.dimdoors]
			driftwood = true

		[types.leaves_type.eidolon_repraised]
			illwood = true

		[types.leaves_type.eternal_starlight]
			lunar = true
			northland = true
			banyin = true
			scarlet = true
			torreya = true
			cradlewood = true

		[types.leaves_type.galosphere]
			opal = true

		[types.leaves_type.goety]
			hardened = true
			rotten = true
			windswept = true
			pine = true
			chorus = true
			chorus_blossom = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.iceandfire]
			dreadwood = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.pastel]
			weeping_gala = true
			nephrite_blossom = true
			spirit_sallow = true
			black = true
			blue = true
			brown = true
			cyan = true
			gray = true
			green = true
			light_blue = true
			light_gray = true
			lime = true
			magenta = true
			orange = true
			pink = true
			purple = true
			red = true
			white = true
			yellow = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true
			pine = true
			flowering_acacia = true

		[types.leaves_type.would]
			willow = true
			baobab = true
			ebony = true
			fir = true
			pine = true
			cedar = true
			mahogany = true
			palm = true
			maple = true
			aspen = true
			walnut = true
			blue_spruce = true

		[types.leaves_type.tropicraft]
			mahogany = true
			palm = true
			kapok = true
			fruit = true
			grapefruit = true
			lemon = true
			lime = true
			orange = true
			papaya = true
			white_flowering = true
			red_flowering = true
			blue_flowering = true
			purple_flowering = true
			yellow_flowering = true
			plantain = true
			jocote = true
			red_mangrove = true
			tall_mangrove = true
			tea_mangrove = true
			black_mangrove = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.hexalia]
			cottonwood = true
			willow = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[entries.stone_type.create]
			cut_wall = true
			small_bricks = true
			layered = true
			cut_brick_wall = true
			pillar = true
			cut_brick_stairs = true
			cut_brick_slab = true
			polished_cut_slab = true
			polished_cut_wall = true
			cut_slab = true
			small_brick_wall = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			cut_stairs = true
			small_brick_stairs = true
			cut_bricks = true
			polished_cut_stairs = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

		[entries.mud_type.betterarcheology]
			cracked_brick_stairs = true
			cracked_bricks = true
			cracked_brick_slab = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			vertical_slab = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.twilightforest]
			drying_rack = true
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true
			hollow_log = true

		[entries.wood_type.woodworks]
			chest = true
			beehive = true
			ladder = true
			trapped_chest = true
			boards = true
			bookshelf = true
			chiseled_bookshelf = true

		[entries.wood_type.decorative_blocks]
			seat = true
			palisade = true
			beam = true
			support = true

		[entries.wood_type.tropicraft]
			boardwalk = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true
